name: "NAIS login"
description: "Login to registry used by the NAIS platform"
inputs:
  team:
    description: "Team slug"
    required: true
outputs:
  registry:
    description: "Registry URL"
    value: ${{ steps.setup.outputs.gar_registry_url }}
runs:
  using: "composite"
  steps:
    - name: Setup environment
      shell: bash
      id: "setup"
      run: |
        slug=${{ inputs.team }}
        prefix="gar"
        maxLength=30

        hash=$(echo -n "$slug" | sha256sum | cut -d ' ' -f 1)

        prefixLength=${#prefix}
        hashLength=4
        slugLength=$((maxLength - prefixLength - hashLength - 2))

        truncatedSlug=$(echo -n "${slug:0:$slugLength}" | sed 's/-$//')
        truncatedHash=$(echo -n "$hash" | head -c $hashLength)

        echo "sa_email=$prefix-$truncatedSlug-$truncatedHash@${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}.iam.gserviceaccount.com" >> $GITHUB_OUTPUT
        echo "gar_registry_url=europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/${{ inputs.team }}" >> $GITHUB_OUTPUT
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1.0.0"
      with:
        workload_identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ steps.setup.outputs.sa_email }}
        token_format: "access_token"
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ steps.setup.outputs.gar_registry_url }}
        username: "oauth2accesstoken"
        password: "${{ steps.auth.outputs.access_token }}"
